<?php
$title = 'Text content';
$this->headTitle($title);
?>
<style>
    /* The Modal (background) */
    .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }

    /* Modal Content/Box */
    .modal-content {
        background-color: #fefefe;
        margin: 15% auto; /* 15% from the top and centered */
        padding: 20px;
        border: 1px solid #888;
        width: 80%; /* Could be more or less, depending on screen size */
    }

    /* The Close Button */
    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }
    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }

    .tooltip {
        visibility: hidden;
        width: 120px;
        background-color: black;
        color: #fff;
        text-align: center;
        border-radius: 6px;
        padding: 5px 0;

        /* Position the tooltip */
        position: absolute;
        z-index: 1;
        //top: -2em;
        //left: 105%;
    }

    .tooltip:hover {
        visibility: visible;
    }
</style>
<h1><?php echo $this->escapeHtml($title) ?></h1>
<div class="row">
    <div class="col-md-5"><h2>Original text</h2></div>
    <div class="col-md-5"><h2>Translation</h2></div>
</div>
<?php foreach ($textSections as $section) { ?>
    <div class="row">
    <div class="col-md-5 original"><ul>
    <li><?php foreach ($section['orig'] as $lineNr => $lineContent) {
        echo $lineContent;
    } ?></li>
    </ul></div>
    <div class="col-md-5 translation"><ul>
    <li><?php foreach ($section['trans'] as $transLineNr => $transLineContent) { ?>
        <?php echo $transLineContent; ?>
    <?php } ?></li>
    </ul></div>
    </div>
<?php }?>



<script type="text/javascript">
    var crossrefs = <?php echo json_encode($crossrefs); ?>;
    var refInfos = <?php echo json_encode($refInfos); ?>;
    console.log(crossrefs);
    console.log(refInfos);
    $(document).on("mouseup", '.word', modalPopup);
    $(document).on("mouseup", '.transl-word', modalPopup);

    var select = document.getElementById('wordtype');
    select.addEventListener('change', updateSubSelect)

</script>